export interface ApiResponse {
  FilmCommonName: string;
  Release_year: string;
  isfranchise: null | string;
  Franchise_tier: string;
  total_revenue: string;
  revenue_label5: string;
  total_seats_sold: number;
  seats_alloted: number;
  total_shows_for_movie: number;
  total_shows_across_city: number;
  genres: string;
  movie_cast: string;
  budget_score: number;
  budget_score_penalized: number;
  revenue_label: string;
  directorRating: number;
  directorReason: string;
  actorRating: number;
  actorReason: string;
  producerRating: number;
  producerReason: string;
  musicDirectorRating21: number;
  musicDirectorReason: string;
  sentimentScore: number;
  sentimentReason: string;
  Total_Score: number;
  classification_label: string;
  one: null | string;
  sentiment_rating: null | number;
  musicdirectorrating29: null | number;
  Franchise_penalization: null | number;
  Franchise_tierbased: number;
  songsRating: number;
  songReason: string;
  audiencePopularityScore: number;
  audiencePopularityReason: string;
  filmGenre: string;
  plotRatingReason: string;
  plotRating: number;
  franchiseRating: number;
  franchiseRatingReason: string;
  genreRating: number;
  genreReason: string;
  oneKindRating: number;
  oneKindReason: string;
  musicRating: number;
  musicReason: string;
  Total_Score_s3: number;
  classification_s3: string;
  revenue_per_show: number;
  revenue_label50: string;
  seatsold_label: string;
  ratio_label: string;
  isControversial: string;
  controversialReason: string;
  isHistoric: string;
  historicTopic: string;
  hasStereotypes: string;
  stereotypesReason: string;
  isReligious: string;
  religiousTopic: string;
  isPolitical: string;
  politicalTopic: string;
  isSensitive: string;
  sensitiveReason: string;
  isPatriotic: string;
  patrioticTopic: string;
  original_language_name: string;
}
